### ISSUE TITLE
Font which width is not a byte multiple won't render

### ISSUE THREAD

**Issue by odudex** [selfcustody/krux#114]
When fonts are baked according to instructions they will render correctly only if its width is a 8 multiple. Ex 8*14, 8*16, 16*32.
Other sizes like 12*24 won't render, because 12 can't be divided by 8. However, if I lie to `py_lcd.c` on config, and say it is a 16*24 font, it will render, with larger space between letters thought.

**Comment by odudex** [comment]
Had some more spare time and solved this issue, all fonts are rendering correctly now [ex: 14x28](https://photos.app.goo.gl/BX6tDcLNE6oziDfDA).
Before a PR, what do you think of a cleanup on font.c and remove those unused features (monospace, scale, x_spacing, y_spacing)

**Comment by jreesun** [comment]
That sounds good to me 👍

**Comment by odudex** [comment]
Done, removed those variables and also all `float` variables and methods (round, ceil, etc) from this part of the code. Also added proper PMU control for Amigo
