### ISSUE TITLE
Add battery life indicator

### ISSUE THREAD

**Issue by jreesun** [selfcustody/krux#145]
Should reside in the same place on all screens and needs to be out of the way of existing text and QR codes. This is likely the bottom of the screen. Will need to be very, very small so it can be used on the M5StickV. 

Perhaps a green/yellow/red box or line?

Easiest way to add to all screens would be to update the `Display.clear` method to immediately draw the indicator on it after clearing.

**Comment by hugoender** [comment]
This shows as completed but is not in the latest build. Any idea when it will be released?
