### ISSUE TITLE
Add printer support to Amigo

### ISSUE THREAD

**Issue by jreesun** [selfcustody/krux#149]
Currently, Krux can only print QR codes via thermal printer with the M5StickV. 

The Amigo should be able to do this too since it has grove connector ports.

**Comment by jreesun** [comment]
@odudex Did you have any luck with this?

**Comment by odudex** [comment]
Sorry, I did not even buy the printer yet. There's a guy in the Telegram group that succeed with another M5STICKV, and others have ordered printers

**Comment by jreesun** [comment]
@odudex You mentioned that you got it working on Amigo. Is this working now with the latest code in `develop`, or are more changes needed before I can close this?

**Comment by odudex** [comment]
Ad I remember, it worked out of the box. I just changed some timing values to get more contrast on my AliExpress printer. For my latest test firmware I also expanded the prints for text, compact SeedQR and Tiny Seed (which is now scannable too, as the real thing). Maybe it's time to clean this new code and make a new PR, I also didn't do pytest for those too😬.
