### ISSUE TITLE
Remove dice roll count restrictions

### ISSUE THREAD

**Issue by jreesun** [selfcustody/krux#174]
After selecting `Via D6` or `Via D20`, add a follow-up prompt asking if the user wants to generate a `12-word` or `24-word` mnemonic.

Then let the user enter as many rolls as they want.

If they enter less than 50 or 99 rolls (or 30/60 for the D20) and select `Go`, display the "Are you sure? Y/N" prompt with a message like "It is strongly recommended to use at least X rolls" preceding it.

Do SeedSigner or ColdCard let users create 12-word mnemonics from dice input? If so, it would be good to know what their upper limits are so we can be consistent with them.

**Comment by qecez** [comment]
> Do SeedSigner or ColdCard let users create 12-word mnemonics from dice input? If so, it would be good to know what their upper limits are so we can be consistent with them.

Yes, they take 50 rolls in for 12 words and 99 for 24.
