### ISSUE TITLE
Broken link in Docs

### ISSUE THREAD

**Issue by tadeubas** [selfcustody/krux#182]
This [generating-a-mnemonic doc page](https://github.com/selfcustody/krux/blob/a846b5a7bc6011b67c034ead7fa869342cb6a761/docs/getting-started/generating-a-mnemonic.en.md) have a broken link to vault12 at the end:
See **here** for a good method to generate a mnemonic manually

The site has changed, I think the correct link is one of these here:
https://vault12.com/securemycrypto/cryptocurrency-security-how-to/seed-phrase-creation/

**Comment by jreesun** [comment]
Fixed by https://github.com/selfcustody/krux/commit/c19c03ed07df845c1408b02e094309b079e55a9f

Thanks!
