### ISSUE TITLE
Live Debug don't work, device resets because of watchdog

### ISSUE THREAD

**Issue by tadeubas** [selfcustody/krux#184]
I've tried to follow the steps here to live debug a MaixDock: https://github.com/selfcustody/krux#live-debug-a-device

Win 10 Pro v 21H2 - AMD x64 processor - USB 2.0
MaixPy IDE 0.2.5 (Tools > Open Terminal)
MaixDock M1 (without wireless, encoder KY-040 soldered)

Everything works but after a while Krux resets the device, the image below shows the terminal running, CRTL+C pressed, some arbitrary math executed and suddenly the Krux watchdog restart:

![image](https://user-images.githubusercontent.com/5518496/217227157-a21a0406-7df1-4fe6-a189-001477c6486e.png)

**Comment by jreesun** [comment]
Makes sense. That's unfortunately the watchdog working as designed. This can be worked around by increasing the `RESET_TIMEOUT` value in `src/wdt.py` during development and testing: https://github.com/selfcustody/krux/blob/main/src/krux/wdt.py#L24 

If this isn't sufficient, there may be a way to modify `maixpy_main.c` in the MaixPy repo to disable the watchdog on interrupt.

**Comment by tadeubas** [comment]
Yes I have disabled it! You just need to add this line on the `src/wdt.py`:
```
wdt.stop()
```

The only problem is that you need to compile the code and flash the device... I will submit a PR complementing this info in README

**Comment by tadeubas** [comment]
I've created a way to disable Krux watchdog without the need to build the project from source (see the open PR).

Instructions are presented at `README`, the user only needs to create a property called `WATCHDOG_DISABLE` in the `config.json`file at the device `/flash` (this is possible to do just before the Krux watchdog resets the device)
