### ISSUE TITLE
Load Mnemonic, Via Numbers and Via Bits options do not show any error when user enters wrong word

### ISSUE THREAD

**Issue by streamofstars** [selfcustody/krux#208]
In option Load Mnemonic, Via Numbers and Via Bits, when a user enters a number out of range and clicks Go, there is no any message that would tell the user that they just entered a wrong word and they need to input it again, Krux just deletes previous input. Yes, there is words counter at the top but I think there should be an explicit message for the user to input last word again because what they just entered is not valid.

**Comment by tadeubas** [comment]
This option to enter the bits of the mnemonic does not exist anymore in the new BETA version, it was replaced by the Tiny Seed import feature, you could check the code here: https://github.com/odudex/krux/ and the binaries here: https://github.com/odudex/krux_binaries
