### ISSUE TITLE
Load Mnemonic, Via Bits, it is possible to input ridiculously long strings

### ISSUE THREAD

**Issue by streamofstars** [selfcustody/krux#209]
Load Mnemonic, Via Bits, it is possible to input ridiculously long string of zeroes and Krux matches that to a word list and proceeds to the next word. E.g. just type in like 20x zeroes and it will be matched to word "abandon" or 20x zeroes and "10" and it will resolve as "abuse". This is technically true (no matter how many prepending zeroes in binary it is always just a decimal zero) but IMHO there should be characters limit to avoid some weird mistakes scenarios like accidental misclicks.

**Comment by odudex** [comment]
"Via Bits" was replaced by Tiny Seed mode on current beta version. You'll have a more intuitive interface where you can correlate each bit with the word it belongs, as well as automatic and dynamic checksum visualization. [Check it out](https://github.com/odudex/krux_binaries)
