### ISSUE TITLE
'Unknown device' when trying to flash Krux onto M5StickV

### ISSUE THREAD

**Issue by hugoender** [selfcustody/krux#210]
Following directions on the website but when I send `vagrant ssh -c 'cd /vagrant; ./krux flash'` I get `Unknown device`. I tried the following:

- reloading vagrant
- adding user to vboxusers using `sudo usermod -a -G vboxusers yourusername`
- going into virtualbox settings of krux VM and adding the M5StickV to the USB list 
- changing virtualbox settings of krux VM to be USB 2.0 instead of USB 1.0

None of those things helped. Any help with this would be greatly appreciated.

**Comment by hugoender** [comment]
Just figured it out. Turns out the krux website (https://selfcustody.github.io/krux/getting-started/installing-from-source/) is incorrect. 

It states the flash command should be `vagrant ssh -c 'cd /vagrant; ./krux flash'` when in fact it should be `vagrant ssh -c 'cd /vagrant; ./krux flash maixpy_DEVICE` similar to the `build` command.

**Comment by hugoender** [comment]
Submitted PR (https://github.com/selfcustody/krux/pull/211) with fix.

**Comment by tadeubas** [comment]
Thx!
