### ISSUE TITLE
M5StickV How to wipe the device / restore to default state?

### ISSUE THREAD

**Issue by streamofstars** [selfcustody/krux#226]
Less Krux more hardware (M5StickV) question but it might be beneficial to everyone to also cover it here. How to wipe the device / restore to default state? In the official hardware documentation (https://docs.m5stack.com/en/core/m5stickv) under easyloader there is a tool for that but it's .exe and I have no access to Windows machine. Also, the web version of that loader hangs on me after connecting. Where do I get the original firmware image that I could load into the device with ktool?

**Comment by odudex** [comment]
I don't know if it is the same firmware M5 ships, but you can find one [here](https://dl.sipeed.com/shareURL/MAIX/MaixPy/release/master/maixpy_v0.6.2_85_g23d09fbcc). There's a firmware specific for m5sitckv on the list.
Instructions to flash using their recommended tool "kflash" [here](https://wiki.sipeed.com/soft/maixpy/en/get_started/upgrade_maixpy_firmware.html)

As this is not Krux related and we won't cover device's specific support I'm closing this issue.
