### ISSUE TITLE
Translation of the error is not working

### ISSUE THREAD

**Issue by aglkm** [selfcustody/krux#247]
1. Switch to non English language
2. Encrypt and save a mnemonic into device flash storage
3. Try to load this mnemonic with the wrong key
4. Notice an error with some or all symbols not translated

**Comment by tadeubas** [comment]
I tried with es-MX and pt-BR, here are the results (the only untranslated part is the type of the error). But I've noticed lots of error messages without the `t()` function, so this means that when those errors happen they will not be translated

![image](https://github.com/selfcustody/krux/assets/5518496/2179fffe-858d-43cb-977c-e4f6db4c9e9a)
![image](https://github.com/selfcustody/krux/assets/5518496/56e8b07a-f88d-4cff-a134-e8ef9cfee04b)

**Comment by odudex** [comment]
Fixed with c812d2ef8abddc4f6028e159981fb872fd8429e8.
Now we know it's better not to use translations when raising errors.
