### ISSUE TITLE
Merge latest upstream of MaixPy into our MaixPy fork

### ISSUE THREAD

**Issue by ghost** [selfcustody/krux#256]
The diff isn't too large:
https://github.com/selfcustody/MaixPy/compare/master...sipeed:MaixPy:master

It looks like it could be safely pulled down into our fork.

Not a high priority, but a good idea to keep it up to date.

**Comment by tadeubas** [comment]
Can we consider this done on [release 24.03.0](https://github.com/selfcustody/krux/releases/tag/v24.03.0) ?

**Comment by odudex** [comment]
Yes, done in [Release v24.03.0](https://github.com/selfcustody/krux/releases/tag/v24.03.0)
