### ISSUE TITLE
Move "Encrypted QRCodes" under Getting Started

### ISSUE THREAD

**Issue by jreesun** [selfcustody/krux#260]
Looks out of place in the top nav bar, would make more sense under "Getting Started" alongside "Printing." 

Printing is similar in that it's not its own section in the UI, but it needed its own page in the docs. Other pages in the docs reference printing but link to the standalone page for more info. I think we should do similar for encrypted QR codes.

Since there are multiple sections like this now, we could make a new subheading under "Getting Started" for things like this: "Features"

```
Getting Started > Features >
  - Printing
  - Transcribing QR codes
  - Encrypted QR codes
```

"Features" is the most general term I can come up with to represent any piece of functionality within Krux that might require a large enough explanation that it shouldn't be inside the UI flow docs pages.

**Comment by odudex** [comment]
Done
