### ISSUE TITLE
[Bug] passphrase QR with apostrophes doesn't scan correctly

### ISSUE THREAD

**Issue by 2oh1** [selfcustody/krux#297]
When scanning a passphrase QR that contains an apostrophe, the apostrophe gets deleted and replaced by the preceding letter.

For example, in a passphrase QR, "they've" scans as "theyyve", which leads to an incorrect wallet (xpub/zpub/etc).

This issue doesn't occur when typing the passphrase manually.  In other words, when typed manually, "they've" is shown and processed correctly as "they've".

I'm running Krux v. 23.09.0 on a Maix Amigo.

Also, just to confirm (since it's a tiny symbol), the ' shown below the # and to the left of the ( is an apostrophe, correct?  Just checking, though I'm sure it is.

**Comment by tadeubas** [comment]
Hi @2oh1 , regarding the characters available to select, they are listed below (yes, it shows an `'` apostrophe below the `#` on the screen):
```
LETTERS = "abcdefghijklmnopqrstuvwxyz"
UPPERCASE_LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
NUM_SPECIAL_1 = "0123456789 !#$%&'()*"
NUM_SPECIAL_2 = '+,-./:;<=>?@[\\]^_"{|}~'
```

**Comment by odudex** [comment]
> [They're / Theyyre](https://imgur.com/a/YAQPeXI)

The QR code contains "They’re" not "They're". Do you see the difference? Krux doesn't have the ’ glyph, only '.

**Comment by 2oh1** [comment]
Interesting!  I had to really zoom the screen to see the difference, but I do.  I typed it with an apostrophe on a Mac.

**Comment by odudex** [comment]
Yes, you did nothing wrong! Good you make these tests and helped to find this potential source of trouble.
