### ISSUE TITLE
[Bug] too much dice rolls (245) doesn't show stats for nerds graph

### ISSUE THREAD

**Issue by tadeubas** [selfcustody/krux#348]
#### Summary

Most of dices 1 and some 20

**Device**
- [ ] Amigo
- [ ] M5stickV
- [X] Dock
- [ ] Bit
- [ ] Yahboom

**Version**
- [ ] Official release (selfcustody/krux): 
- [X] Beta release (odudex/krux_binaries):  

#### Describe the bug

When generating a new mnemonic rolling d20 dices, when most of dices gives 1 and few gives 20, with 245 rolls the `stats for nerds` doesn't show rolls distribution graph correctly

![image](https://github.com/selfcustody/krux/assets/5518496/98ff9c69-eee3-4a81-adbf-847cd6488722)

**Comment by odudex** [comment]
Fixed with 29b94686f7e6c786f0aea632c5950a3c6674e012
Please let me know otherwise.
