### ISSUE TITLE
[Enhancement] Cube some pages don't use the full screen

### ISSUE THREAD

**Issue by tadeubas** [selfcustody/krux#349]
Some pages uses only half of the screen on Cube, like it was running on a M5stickV

**Device**
- [ ] Amigo
- [ ] M5stickV
- [ ] Dock
- [ ] Bit
- [ ] Yahboom
- [X] Cube

**Version**
- [ ] Official release (selfcustody/krux): 
- [X] Beta release (odudex/krux_binaries):  

#### Describe the bug

On cube or simulator:

- `Load Mnemonic > Via Manual Input > Tiny Seed (Bits) > 12 words` (uses only half of the screen)

![image](https://github.com/selfcustody/krux/assets/5518496/97e7a080-017a-49a0-a1e8-69c0086c24f8)

- `Load Mnemonic > Via Manual Input > Tiny Seed (Bits)` (could increase size usage like in other devices)

![image](https://github.com/selfcustody/krux/assets/5518496/12067d1c-1372-4887-8847-b4133267ce9f)

- `Backup Mnemonic > Other formats > Stackbit 1248` (doesn't show the extra info like other larger devices)

![image](https://github.com/selfcustody/krux/assets/5518496/d9038a27-d6e0-44c2-a814-bc69c791da86)

- `Backup Mnemonic > Other formats > Tiny Seed` (uses only half of the screen)

![image](https://github.com/selfcustody/krux/assets/5518496/765f0064-ab83-492b-86f8-f8c5c97a072c)

**Comment by odudex** [comment]
I see the enhancements opportunities but, for the sake of priority, what exactly is the bug?

**Comment by tadeubas** [comment]
Lol, I will change it to Enhancement 😉

**Comment by odudex** [comment]
Done
