### ISSUE TITLE
Add Continuous navigation

### ISSUE THREAD

**Issue by BitcoinMaranhao** [selfcustody/krux#364]
Adding continuous navigation to increase the keyboard typing experience and the lifetime of device buttons.

**Comment by tadeubas** [comment]
Just a little context:

- This is for the Cube device, when moving the wheel left/right and holding it for some time it will automatically move to the next option until the user releases

**Comment by odudex** [comment]
Added in cbac036effb71b760bac2d63752e110ba37a511a
