### ISSUE TITLE
env for poetry

### ISSUE THREAD

**Issue by j-moreno-c-r** [selfcustody/krux#377]
a proposal of solution for the problem of  the pip installation poetry, in the README.md, the solution is, run the "pip install poetry" inside a python venv....

**Comment by j-moreno-c-r** [comment]
There may be a problem at this stage when trying to directly install Poetry, we have a solution proposal(this comands are for the unix system mac or linux):
In a local directory run(we consider the name of the venv .krux but you can change this...):
```bash
python -m venv .krux
source .krux/bin/activate
```
The result will be something like:
```bash
(.krux) username:~/directory name$ 
```
Now you can run normaly the pip of the poetry:
```bash
pip install poetry
poetry install
```

**Comment by tadeubas** [comment]
plz create a PR to branch `wallet_customization`: https://github.com/selfcustody/krux/pulls

**Comment by j-moreno-c-r** [comment]
ok

**Comment by odudex** [comment]
Instructions for this workaround added to docs.
