### ISSUE TITLE
[Bug] BIP85 "Load child?" translations doesn't fit screen

### ISSUE THREAD

**Issue by tadeubas** [selfcustody/krux#431]
#### Summary

![image](https://github.com/user-attachments/assets/439f5577-c205-40d1-b428-8d590a46a658)

![image](https://github.com/user-attachments/assets/780322ca-8256-4b0e-9593-5378cb3bb6ad)

**Device**
- [ ] Amigo
- [x] M5stickV
- [ ] Dock
- [ ] Bit
- [ ] Yahboom
- [x] Cube

**Version**
- [x] Official release (selfcustody/krux): v24.07.0 
- [ ] Beta release (odudex/krux_binaries):  

#### Describe the bug

BIP85 "Load child?" translations doesn't fit some device's screen.

Translations affected:

- fr-FR
- nl-NL
- pl-PL
- ru-RU
- tr-TR
- vi-VN

**Comment by tadeubas** [comment]
My suggestion is to simplify this string to "Load?" like we have on other screens

**Comment by odudex** [comment]
Solved with #433
