### ISSUE TITLE
[Bug] Maix Cube camera is inverted in version 24.09.0

### ISSUE THREAD

**Issue by mikeyb233** [selfcustody/krux#460]
#### Describe the bug
After performing an air-gapped update using version 24.09.0 the Maix Cube camera is now inverted.

**Device(s) affected**

- [ ] Cube

**Version affected**
- [ ] Official release (selfcustody/krux): v24.09.0

**Comment by odudex** [comment]
Could you please test the fix? set as pre-release on:
https://github.com/selfcustody/krux/releases/tag/v24.09.1

**Comment by mikeyb233** [comment]
That fixed it. Updated the same way via airgap using v24.09.1 and the camera orientation is correct.

Thank you!

**Comment by odudex** [comment]
Fixed with 2bbc533fabaa3160c70f9979fe1c0740715b8cb7
