### ISSUE TITLE
Add optional game of breakout to boot screen

### ISSUE THREAD

**Issue by jreesun** [selfcustody/krux#77]
On boot, a game of breakout starts where you need to get a certain score to "beat" the game and land on the Krux start menu.

Mostly a fun gimmick, but could maybe be useful in certain situations.

**Comment by kkdao** [comment]
Good idea, that's what [this](https://github.com/arcbtc/bowser-bitcoin-hardware-wallet) project uses as well. Along with another neat feature which has users enter a PIN using morse code. 

The project mentioned the bowser game on boot as being something useful when traveling abroad.

**Comment by jreesun** [comment]
Closing in favor of https://github.com/selfcustody/krux/issues/203
